### ISSUE TITLE
Can not set [Whole Match Mode] to default mode

### ISSUE THREAD

**Issue by pkokp8** [ryu1kn/vscode-text-marker#19] opened 2018-06-20 07:12 UTC
It is Non-Whole Match Mode and Case Sensitive Mode in default.
I want to set Whole Match Mode and Case Insensitive Mode in default, but after I set it by click the button in status bar or command, my setting will be lost when I restart the vscode.
Is there any way to save my setting?
It is happened when I save the workspace even I haven't restart the vscode

system: windows7
vscode:1.24.1
textmarker:1.1.0

**Comment by pkokp8** [comment] 2018-06-20 07:22
By the way,  the highlight will be lost after I saved the workspace

**Comment by ryu1kn** [comment] 2018-06-20 08:51
Hi @pkokp8 . Yeah we don't have a configuration for setting the default matching mode. It will be a helpful addition. Thanks for the suggestion.

As for the symptom highlight not being saved, I could not reproduce it, i.e. I could save highlight to my workspace settings by using `TextMarker: Save All Highlights` command without problems. If you still see the issue, can you open another issue with the steps to reproduce? Thanks!

**Comment by pkokp8** [comment] 2018-06-21 02:32
Sorry that I don't know `TextMarker: Save All Highlights`.
It works, Thank you!

**Comment by ryu1kn** [comment] 2018-06-22 10:12
Released as v1.3.0! 🎉

**Closed by ryu1kn** 2018-06-22 10:12 UTC
Labels: enhancement

**Comment by pkokp8** [comment] 2018-07-04 09:40
Thanks！
